################################################################################
# Abstract:
# Main docker-compose implimentation of mokafelk
#
# Description:
#
#
# Copyright (c) 2016 Lingxiao Xia [s1006595991 at gmail dot com]
# Project: mokafelk
# Creation: Lingxiao Xia
# Creation Date: 2015-02-03
################################################################################
version: '2'

services:
    input:
        build: ./input
        volumes:
            - ./input/config/:/tmp/mokafelk/logstash/config
            - ./input/src/:/tmp/mokafelk/logstash/src
            - ./input/log/:/tmp/mokafelk/logstash/log
        hostname: input
        restart: always

    logstash:
        build: ./logstash
        volumes:
            - ./logstash/config/:/tmp/mokafelk/logstash/config
            - ./logstash/log/:/tmp/mokafelk/logstash/log
        hostname: logstash
        restart: always

networks:
    default:
        external:
            name: {{ project_id }}_default
